// svelte-kit-todo-app-with-redis/src/routes/index.svelte
<script lang="ts">
  import "../app.css";
  import type { Todo } from "$lib/types";
  import TodoItem from "../components/Todo.svelte";

  export let todos: Todo[];
  const uncheckedTodos = todos.filter((todo) => !todo.status);
  const checkedTodos = todos.filter((todo) => todo.status);
</script>

<svelte:head>
  <title>Todos</title>
</svelte:head>

<main class="container">
  <form class="new" action="/" method="post">
    <input
      type="text"
      name="text"
      autofocus
      aria-label="Add todo"
      class="input"
      placeholder="What needs to be done?"
    />
  </form>

  <div class="todos">
    {#each uncheckedTodos as todo (todo.id)}
      <TodoItem {todo} />
    {/each}
  </div>

  {#if checkedTodos.length}
    <div class="todos todos-done">
      {#each checkedTodos as todo (todo.id)}
        <TodoItem {todo} />
      {/each}
    </div>
  {/if}
</main>

<style>
  .todos {
    margin-top: 1.5rem;
  }

  .todos.todos-done {
    background-color: var(--gray-100);
    color: var(--gray-500);
    border-radius: var(--rounded-md);
  }
</style>

// remix-todo-app-with-redis/app/routes/index.tsx
import type { ActionFunction, LoaderFunction } from "remix";
import type { Todo } from "~/components/todo-item";
import { Form, useLoaderData, useTransition, redirect } from "remix";
import TodoItem from "~/components/todo-item";
import { fetchData, insertOrUpdateData } from "~/utils/database";
import { useEffect, useRef } from "react";

export const loader: LoaderFunction = async () => {
  return await fetchData();
};

export const action: ActionFunction = async ({ request }) => {
  const form = await request.formData();

  if (request.method === "POST") {
    const text = form.get("text");
    if (!text) return redirect("/");

    const id = Date.now().toString();
    await insertOrUpdateData(id, { text, status: false });
  }

  if (request.method === "PUT") {
    const todo = form.get("todo");
    const { id, text, status } = JSON.parse(todo as string);
    await insertOrUpdateData(id, {
      text,
      status: !status,
    });
  }

  return redirect("/");
};

export default function Index() {
  const transition = useTransition();
  const todos: Todo[] = useLoaderData();

  const isCreating = transition.submission?.method === "POST";
  const isAdding = transition.state === "submitting" && isCreating;

  const uncheckedTodos = todos.filter((todo) => !todo.status);
  const checkedTodos = todos.filter((todo) => todo.status);

  const formRef = useRef<HTMLFormElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (isAdding) return;
    formRef.current?.reset();
    inputRef.current?.focus();
  }, [isAdding]);

  return (
    <main className="container">
      <Form ref={formRef} method="post">
        <input
          ref={inputRef}
          type="text"
          name="text"
          autoComplete="off"
          className="input"
          placeholder="What needs to be done?"
          disabled={isCreating}
        />
      </Form>

      <div className="todos">
        {uncheckedTodos.map((todo) => (
          <TodoItem key={todo.id} {...todo} />
        ))}
      </div>

      {checkedTodos.length > 0 && (
        <div className="todos todos-done">
          {checkedTodos.map((todo) => (
            <TodoItem key={todo.id} {...todo} />
          ))}
        </div>
      )}
    </main>
  );
}
